[project]
name = "comfyui-dhan-maskingadv"
version = "0.1.0"
description = "Advanced image masking and editing node for ComfyUI."
license = { file = "LICENSE" }
dependencies = []

[project.urls]
Repository = "https://github.com/DHan315/Comfyui-DHan-MaskingADV"
"Bug Tracker" = "https://github.com/DHan315/Comfyui-DHan-MaskingADV/issues"

[tool.comfy]
PublisherId = "dhan315"
DisplayName = "Comfyui-DHan-MaskingADV"

